- hosts: remote-server
  gather_facts: false
  become: true
  tasks:
    - name: getting jenkins admin password at first log in 
      shell: sudo kubectl logs  $(sudo kubectl get pods -n tools | grep -i jenkins* | awk '{ print $1 }') -n tools | grep -A2 -P '^Please use the following password*' | sed -n 3p
      register: jenkinspass
   
    - name: getting nexus admin password at first log in 
      shell:  sudo kubectl exec -it  $(sudo kubectl get pods -A | grep -i nexus* | awk '{ print $2 }') -n tools -- bash -c "cat /nexus-data/admin.password"
      register: nexuspass
    
    - name: getting nexus service repo ip 
      shell:  kubectl get svc -n tools | grep -i nexus-repo-svc1 | awk '{ print $3 }'
      register: nexusserviceip
    

- hosts: localhost
  gather_facts: false
  tasks: 
    - copy:
        dest: "./file.txt"
        content:  "{{ hostvars[groups['remote-server'][0]]['jenkinspass']['stdout'] }} \
                   {{ hostvars[groups['remote-server'][0]]['nexuspass']['stdout'] }}   \
                   {{ hostvars[groups['remote-server'][0]]['nexusserviceip']['stdout'] }}
                   " 
    - command: sed -i -e 's/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/'"{{ hostvars[groups['remote-server'][0]]['nexusserviceip']['stdout'] }}"'/g'  ../CI-CD/app.yaml
    
