apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: db
  name: db-pod
  namespace: dev
spec:
  containers:
  - image: mysql:5.7
    name: db-pod
    ports:
      - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            key: MYSQL_ROOT_PASSWORD
            name: db-secret
      - name: MYSQL_DATABASE
        valueFrom:
          secretKeyRef:
            key: MYSQL_DATABASE
            name: db-secret
    volumeMounts:
      - mountPath: "/var/lib/mysql"
        name: db-pv
    resources: {}
  restartPolicy: Always
  volumes:
    - name: db-pv
      persistentVolumeClaim:
        claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc 
  namespace: dev
spec:
  selector:
    tier: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi